/******************************************************************************
 DO NOT EDIT - This file is generated by the SysConfig tool.
 @file ti_154stack_config.c

 @brief TI-15.4 Stack configuration parameters for Sensor
 coexistence applications

 *****************************************************************************/

 /******************************************************************************
 Includes
 *****************************************************************************/
 #include <ti/drivers/rf/RF.h>
 #include "mac.h"

/*
 *  ========================== 15.4 Stack Coex Config ==========================
 */

/*
 * 3-wire coexistence not enabled in this application
 */
