/******************************************************************************
 DO NOT EDIT - This file is generated by the SysConfig tool.
 @file ti_154stack_features.h

 @brief TI-15.4 Stack feature parameters definitions for sensor applications

 *****************************************************************************/
#ifndef TI_154STACK_FEATURES_H
#define TI_154STACK_FEATURES_H

#ifdef __cplusplus
extern "C"
{
#endif

/* Builds the image with the MAC layer security turned on */
#define FEATURE_MAC_SECURITY

/* Builds the image with non beacon mode of operation */
#define FEATURE_NON_BEACON_MODE


#ifdef __cplusplus
}
#endif

#endif /* TI_154STACK_FEATURES_H */
